#所有参数的配置，冒号后面必须有一个空格

#配置tomcat的端口
server:
  port: 8088
  servlet:
    #项目访问路径
    context-path: /WeChatSmallProgram/wx/
    #session的有效期为30分钟，m分钟，s秒
    session:
      timeout: 30m

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/houserental?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    druid:
      #配置监控url
      stat-view-servlet:
        #连接池的监控地址
        url-pattern: /druid/*
        #登录名
        login-username: root
        #登录密码
        login-password: 123456
        enabled: true
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,slf4j


  http:
    #设置字符编码
    encoding:
      charset: UTF-8

  # Redis配置
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    #redis连接信息
    port: 6379
    host: localhost
    password:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis连接超时时间（单位：毫秒）
    timeout: 5000ms
    jedis:
      pool:
        # Redis连接池最大连接数（使用负值表示没限制）
        max-active: 1000
        # Redis连接池最大阻塞等待时间（使用负值表示没限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5

#mybatis配置(dao在启动类用@MapperScan注解配置)
mybatis-plus:
  type-aliases-package: com.example.wechatsmallprogram.entity
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      #逻辑已删除值(默认为 1)
      logic-delete-value: 1
      #逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
    banner: false
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


upload:
  filePath: d:\parkPic\
  excelPath: d:\parkPic\Excel\
  prefix: http://localhost:8088/WeChatSmallProgram/

servlet:
  multipart:
    #文件上传单个文件的大小
    max-file-size: 4MB
    max-request-size: 20MB

wx:
  miniapp:
    appid: wxefa785fe6e0d5531
    secret: 395a2512669534fdb8352cf8debf8856